### ISSUE TITLE
3月31日出校报备失效

### ISSUE THREAD

**Issue by vonfzm** [Kobe972/USTC-ncov-AutoReport#1]
以前报备是选校区，t：3，现在变成了先t：3然后下个页面选校区。
另外能否增加第一天晚上八点后报备到第二天的选项？谢谢！

**Comment by flynnnfif** [comment]
今天是30日23333

**Comment by Kobe972** [comment]
> 以前报备是选校区，t：3，现在变成了先t：3然后下个页面选校区。 另外能否增加第一天晚上八点后报备到第二天的选项？谢谢！

源代码里的请求经测试仍然能用，但保险起见对部分URL进行了更新。报备失效主要是增加了宿舍信息，现已修改。如果需要提前一天打卡，在[report.yml](https://github.com/Kobe972/USTC-ncov-AutoReport/blob/master/.github/workflows/report.yml)里仿照原来格式修改或增加一个cron即可（注意cron是UTC时间而不是北京时间）。
